# SPDX-FileCopyrightText: 2024 Andrew Pantuso <ajpantuso@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dyn-radius
configMapGenerator:
- name: server
  literals:
  - validUsers=test-user
  files:
  - allowedClientSources
secretGenerator:
- name: server
  literals:
  - client-secret=testing123
  - totp-secret=ONSWG4TFOQ======
resources:
- ../../base
- namespace.yaml
