# SPDX-FileCopyrightText: 2024 Andrew Pantuso <ajpantuso@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  externalTrafficPolicy: Local
  ports:
  - name: auth
    port: 1812
    targetPort: auth
    protocol: UDP
